CREATE DATABASE IF NOT EXISTS legacy_staging;
USE legacy_staging;
CREATE TABLE IF NOT EXISTS `customers` (
  `CUST_ID` INT NULL,
  `NAME` VARCHAR(30) NULL,
  `CITY` VARCHAR(20) NULL,
  `PHONE` VARCHAR(15) NULL
);

CREATE TABLE IF NOT EXISTS `employees` (
  `EMP_ID` INT NULL,
  `EMP_NAME` VARCHAR(30) NULL,
  `DEPT` VARCHAR(20) NULL,
  `DOJ` DATE NULL,
  `ACTIVE` BOOLEAN NULL
);

CREATE TABLE IF NOT EXISTS `orders` (
  `ORDER_ID` INT NULL,
  `CUST_ID` INT NULL,
  `ORDER_DT` DATE NULL,
  `AMOUNT` DECIMAL(10,2) NULL
);

CREATE TABLE IF NOT EXISTS `products` (
  `PROD_ID` INT NULL,
  `PROD_NAME` VARCHAR(40) NULL,
  `PRICE` DECIMAL(10,2) NULL,
  `STOCK` INT NULL
);

